GET http:localhost:3000/reservations

GET http:localhost:3000/reservations/674ecac33000dd990695ebed

POST http://localhost:3000/reservations
Content-Type: application/json

{
  "startDate": "12/20/2022",
  "endDate": "12/25/2022",
  "placeId": "12345",
  "invoiceId": "493",
  "charge" : {
    "amount": 5,
    "card": {
      "cvc": "413",
      "exp_month": 12,
      "exp_year": 2027,
      "number": "4242 4242 4242 4242"
    }
  }
}

DELETE http://localhost:3000/reservations/676987da0ae257e813744b7d